[metadata]
creation_date = "2020/08/24"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/11/03"

[rule]
author = ["Elastic"]
description = """
Identifies suspicious instances of WerFault or Wermgr with null commandline value, this may indicate an attempt to evade
suspicious child processes related behavior detections.
"""
false_positives = ["Legit Application Crash with rare Werfault commandline value"]
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Process Potentially Masquerading as Windows Error Manager"
references = [
    "https://twitter.com/SBousseaden/status/1235533224337641473",
    "https://www.hexacorn.com/blog/2019/09/20/werfault-command-line-switches-v0-1/",
]
risk_score = 47
rule_id = "6ea41894-66c3-4df7-ad6b-2c5074eb3df8"
severity = "medium"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Defense Evasion"]
type = "query"

query = '''
event.category:process and event.type:(start or process_started) and
 process.name:(WerFault.exe or wermgr.exe) and process.args_count : 1
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1036"
name = "Masquerading"
reference = "https://attack.mitre.org/techniques/T1036/"


[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

